### ISSUE TITLE
Mathematical operators cause unexpected behaviours

### ISSUE THREAD

**Issue by Armitxes** [SkaceKamen/vscode-sqflint#3] opened 2016-12-04 13:08 UTC
Hello @SkaceKamen, 

I've found 2 issues regarding mathematical operators that break your plugin in the current file
- [ ] Using operators on commands (such as "time") breaks any futher debugging (this bug, breaks the debugger out of its current scope)

Example:
This is a perfectly legit script-code. Yet you notice that not only the "else" statement is marked as error but also all follwing "case" statements and closing brackets. This is all caused by the "-3" behind the time command.
![sqflint_mo_breack](https://cloud.githubusercontent.com/assets/6265296/20866289/2aac101a-ba2a-11e6-9843-388d173d86ee.PNG)

- [ ]  While `_varC =_varA - varB` is not marked as an error, `_varC = -varB` is.

I often use mathematical operators like this with parameters which results me in having false errors in the console and debugger. Example:
![sqflint_mathematicaloperators](https://cloud.githubusercontent.com/assets/6265296/20866305/b7c55024-ba2a-11e6-92e9-dbc8b99effa1.PNG)

Hope it's not too hard to fix ;) Great project btw. will, try to raise more attention on it.
/ Armitxes

**Comment by SkaceKamen** [comment] 2016-12-04 14:23
I see where the problem is. It parses -5 as "-5" rather than "-" and "5".
Until I publish update and fix the parser, you can fix it by putting space between the oprator. (`time - 5` instead of `time-5`).

**Comment by SkaceKamen** [comment] 2016-12-04 14:37
It'll be fixed in next release, which will hopefully be tonight.

**Closed by SkaceKamen** 2016-12-04 14:37 UTC
